### ISSUE TITLE
Caching not working if CacheKey is complex object

### ISSUE THREAD

**Issue by SOFSPEEL** [Respawnsive/Apizr#26]
I have caching setup as follows for the complex object LinkRequest

```

  [Post("/api/v5/domains/{domainUuid}/links"), Cache(CacheMode.GetOrFetch, "06:00:00")]
   Task<LinkResponse> CreateLinkAsync([Body] [CacheKey("LongUrl")] LinkRequest request, string domainUuid);

```

```
public class LinkRequest
{
    public LinkRequest()
    {
    }

    public LinkRequest(string longUrl, string tagName)
    {
        LongUrl = longUrl;
        Tags = [tagName];
    }
    
    [JsonProperty("long_url")] public string LongUrl { get; set; }
    
    [JsonProperty("dupe_check")]
    public int DupeCheck { get; set; } = 1;

    [JsonProperty("tags")]
    public string[] Tags { get; set; }
}
```

My understanding is that if caching is setup this way then the **LongUrl property value** would be included as part of the cache key.

However I get the following exception when its setup this way:

```
System.Reflection.TargetParameterCountException : Parameter count mismatch.
   at System.Reflection.MethodBaseInvoker.ThrowTargetParameterCountException()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Apizr.Extending.ObjectExtensions.ToString(Object source, String keyValueSeparator, String sequenceSeparator)
   at Apizr.ApizrManager`1.GetParameterKeyValues(String parameterName, Object parameterValue)
   at Apizr.ApizrManager`1.IsMethodCacheable[TResult](MethodDetails methodDetails, Expression restExpression, CacheAttributeBase& cacheAttribute, String& cacheKey)
   at Apizr.ApizrManager`1.ExecuteAsync[TApiData](Expression`1 executeApiMethod, Action`1 optionsBuilder)
   at Fundraising.BLL.Providers.UrlShorten.BlinkUrlAndQRCodeV5Provider.ShortenAsync(String url) in 
```

It's possible I'm not understanding how to setup this scenario, i.e. where I want the properties of the complex object to be make up the cache key, if so please provide advise on how to set this up properly, thanks.

I'm on the nuget version 6.2  

<img width="588" alt="image" src="https://github.com/user-attachments/assets/d9e9285f-51b2-4a4e-96af-13704ab53620">

**Comment by JeremyBP** [comment]
Hi and thank you for reporting this.

Just pushed the fix on dev branch, plus some improvements like capability to set multiple properties and not just a single one.

I'll release a v6.3 on NuGet with it and some other things later this week, probably on Thursday.

As a workaround while waiting for 6.3 if needed, note that you can override the ToString() method of your LinkRequest to control the cache key structure of it. Something like I did on my test [here](https://github.com/Respawnsive/Apizr/blob/34756bc9f4cbc2b0059612f2b9988729fd3764f3/Apizr/Tests/Apizr.Tests/Models/ReadAllUsersParams.cs#L29).

**Comment by SOFSPEEL** [comment]
@JeremyBP please note that I had tried the override ToString() method and although it didn't ex out, the cache functionality still wasn't working. I tested this quickly by putting a breakpoint (BP) to the ToString method and the BP didn't hit.

**Comment by JeremyBP** [comment]
Ok so now v6.3.0 is live, I'll let you give it a new try after update and tell me.

On my side, after the fix, it worked like a charm.

I added a new test close to your needs like:
```csharp
[Post("/{path}"), Cache]
Task<User> CreateUser([Body, CacheKey("Email")] User user, string path);
```

where User is:
```csharp
public record User
{
    [JsonPropertyName("id")] public string Id { get; init; }
    [JsonPropertyName("first_name")] public string FirstName { get; init; }
    [JsonPropertyName("last_name")] public string LastName { get; init; }
    [JsonPropertyName("avatar")] public string Avatar { get; init; }
    [JsonPropertyName("email")] public string Email { get; init; }

    /// This is needed to prevent from json serialized result of ToString
    public override string ToString() => base.ToString();
}
```
>[!NOTE]
>I had to override ToString method so that it returns base default type fullname instead of json representation. If not, Apizr will use the json representation as cache key with all properties in, even if you specified property names. Maybe I should say something about it on doc.

Also, note that I did not work that much on Post caching until now, but focused on Get one, as I never had to deal with [such requirement](https://medium.com/@shiny.shubham/caching-post-requests-a8401c1e2e41). That said, I understand it could be useful in real world and hopefully, the cache management code was close to that goal.

If it's still the same, please try to send me a reproduction sample so that I could investigate deeper.

**Comment by JeremyBP** [comment]
Closing this issue, assuming no answer meaning pb fixed by v6.3.0. If not, please just tell me.

**Comment by SOFSPEEL** [comment]
Sorry @JeremyBP, was only able to get to this today, tried with version 6.3

So still not getting this working, when I call CreateLinkAsync twice with **different** LongUrl's in each call, I expect 2 SendAsync calls to go out on my MessageHandler. I'm only seeing one call go out implying that caching is kicking in when it shouldn't.

Also I expect the LongUrl getter to be invoked by apizr cachine and not seeing that in debugger. So it looks like its still ignoring the LongUrl CacheKey.

Note too that compared with your test above I have **CacheMode.GetOrFetch** but your example above shows no caching [Post("/{path}"), Cache], i.e. doesn't this mean Cache.None?

```
   [Post("/api/v5/domains/{domainUuid}/links"), **Cache(CacheMode.GetOrFetch, "06:00:00")**]
    Task<LinkResponse> CreateLinkAsync([Body, CacheKey("LongUrl")] LinkRequest request, string domainUuid);
```

```
public class LinkRequest
{
    public LinkRequest()
    {
    }

    public LinkRequest(string longUrl, string tagName)
    {
        LongUrl = longUrl;
        Tags = [tagName];
    }
    
    [JsonProperty("long_url")] public string LongUrl { get; set; }
    
    [JsonProperty("dupe_check")]
    public int DupeCheck { get; set; } = 1;

    [JsonProperty("tags")]
    public string[] Tags { get; set; }

    /// This is needed to prevent from json serialized result of ToString
    public override string ToString() => base.ToString();
}

```

**Comment by JeremyBP** [comment]
Ok, that makes me think about #20. Well it's holiday time this week for me, but I'll push a fix next week with v6.4.0-preview.2

**Comment by JeremyBP** [comment]
Just pushed v6.4.0-preview.2 on NuGet preview channel.
Please give it a try and tell me if we made any progress about your issue.

I managed to reproduce your bug by setting the cache mode to GetOrFetch on a POST request as you suggested.
Apizr manager wasn't [checking the right cache mode](https://github.com/Respawnsive/Apizr/commit/84cfab492087342b0423367435bd7d135c7dcc68#diff-4d57fac06d11c28eac086b772e60a54005e028c7e6221c9b75a27987c9653efcL626) when sending a POST request with cached result.
My new [tests](https://github.com/Respawnsive/Apizr/blob/01cbd283ef6de7d5f1207f9a5cb03dcaa6adaff8/Apizr/Tests/Apizr.Tests/ApizrTests.cs#L517) pass all green now with that check change 
But who knows...

**Comment by SOFSPEEL** [comment]
Hi @JeremyBP , did some quick testing, so far so good, will do some further testing and anticipate I will be able to close out, thx 4 your efforts!

**Comment by SOFSPEEL** [comment]
@JeremyBP, I thought I was losing my mind for a second, there that because **this works**:

```
   var linkRequest = new LinkRequest(url, _tag);
        var linkResponse = await _apizr.ExecuteAsync(api => api.CreateLinkAsync(linkRequest, _domainUuid))
            .ConfigureAwait(false);
```
and this newing up in the ExecuteAsync **doesn't**:
```
var linkResponse = await _apizr.ExecuteAsync(api => api.CreateLinkAsync(new LinkRequest(url, _tag), _domainUuid))
            .ConfigureAwait(false);
```

**Comment by JeremyBP** [comment]
Yeah that's because of the Expression Tree structure that doesn't allow me to evaluate such a request with inline param instance.
A pitfall I should talk about somewhere in the doc.
And maybe try to find some kind of fix/workaround if possible.

**Comment by JeremyBP** [comment]
I finally pushed a preview 3 with such a cache key generation feature from inline parameter initialization within the ExecuteAsync call:
```csharp
var linkResponse = await _apizr.ExecuteAsync(api => api.CreateLinkAsync(new LinkRequest(url, _tag), _domainUuid))
            .ConfigureAwait(false);
```
So now it should work.
There's still a pitfall anyway about that: no ToString override capability (beacause I don't want to compile the expression to get access to ToString method in such scenario).

So:
- If you need to control the cache key format by overriding the ToString, instanciate the parameter before providing it to the ExecuteAsync, just like you did. 
- If you only need to control the properties selection of your complexe type, consider using the CacheKey attribute with its property names array parameter.
- If you do not need such a custom control over cache key format, just let Apizr generate the cacke key.
